// customers
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';

// employees
export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';

// groupmemberships
export const LOAD_GROUPMEMBERSHIP_SUCCESS = 'LOAD_GROUPMEMBERSHIP_SUCCESS';
export const UPDATE_GROUPMEMBERSHIP_SUCCESS = 'UPDATE_GROUPMEMBERSHIP_SUCCESS';
export const CREATE_GROUPMEMBERSHIP_SUCCESS = 'CREATE_GROUPMEMBERSHIP_SUCCESS';
export const DELETE_GROUPMEMBERSHIP_SUCCESS = 'DELETE_GROUPMEMBERSHIP_SUCCESS';

// intakes
export const LOAD_INTAKES_SUCCESS = 'LOAD_INTAKES_SUCCESS';
export const UPDATE_INTAKE_SUCCESS = 'UPDATE_INTAKE_SUCCESS';
export const CREATE_INTAKE_SUCCESS = 'CREATE_INTAKE_SUCCESS';
export const DELETE_INTAKE_SUCCESS = 'DELETE_INTAKE_SUCCESS';

// invites
export const LOAD_INVITES_SUCCESS = 'LOAD_INVITES_SUCCESS';
export const UPDATE_INVITE_SUCCESS = 'UPDATE_INVITE_SUCCESS';
export const CREATE_INVITE_SUCCESS = 'CREATE_INVITE_SUCCESS';
export const DELETE_INVITE_SUCCESS = 'DELETE_INVITE_SUCCESS';

// messages
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const UPDATE_MESSAGES_SUCCESS = 'UPDATE_MESSAGES_SUCCESS';
export const CREATE_MESSAGES_SUCCESS = 'CREATE_MESSAGES_SUCCESS';
export const DELETE_MESSAGES_SUCCESS = 'DELETE_MESSAGES_SUCCESS';

// notifications
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';

// organizations
export const LOAD_ORGANIZATIONS_SUCCESS = 'LOAD_ORGANIZATIONS_SUCCESS';
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS';
export const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS';

// organizationroles
export const LOAD_ORGANIZATIONROLES_SUCCESS = 'LOAD_ORGANIZATIONROLES_SUCCESS';
export const UPDATE_ORGANIZATIONROLE_SUCCESS = 'UPDATE_ORGANIZATIONROLE_SUCCESS';
export const CREATE_ORGANIZATIONROLE_SUCCESS = 'CREATE_ORGANIZATIONROLE_SUCCESS';
export const DELETE_ORGANIZATIONROLE_SUCCESS = 'DELETE_ORGANIZATIONROLE_SUCCESS';

// questions
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';

// tasks
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

// authentication
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
